// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// baseSVD
arma::vec baseSVD(const arma::mat& X);
RcppExport SEXP _TESSA_baseSVD(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(baseSVD(X));
    return rcpp_result_gen;
END_RCPP
}
// invert
arma::mat invert(const arma::mat& X);
RcppExport SEXP _TESSA_invert(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(invert(X));
    return rcpp_result_gen;
END_RCPP
}
// TT_cpp
double TT_cpp(const arma::mat& M1, const arma::mat& M2);
RcppExport SEXP _TESSA_TT_cpp(SEXP M1SEXP, SEXP M2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type M1(M1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M2(M2SEXP);
    rcpp_result_gen = Rcpp::wrap(TT_cpp(M1, M2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TESSA_baseSVD", (DL_FUNC) &_TESSA_baseSVD, 1},
    {"_TESSA_invert", (DL_FUNC) &_TESSA_invert, 1},
    {"_TESSA_TT_cpp", (DL_FUNC) &_TESSA_TT_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_TESSA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
